# Generated by Django 2.2 on 2019-05-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notf_type',
            field=models.CharField(default='', max_length=25),
        ),
    ]
